version: "3"

services:
  user-server:
    build: ./userService
    container_name: userService
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    restart: on-failure

  mail-server:
    build: ./emailService
    container_name: emailService
    ports:
      - "5001:5001"
    depends_on:
      - memphis-rest-gateway
    restart: on-failure

  redis:
    image: redis:7.0.10-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
    restart: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    ports:
      - "27017:27017"

  memphis-metadata:
    image: memphisos/memphis-metadata:15-docker
    container_name: memphis-metadata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U memphis -p 5005" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5005:5005'
    restart: on-failure
    environment:
      - POSTGRESQL_USERNAME=memphis
      - POSTGRESQL_PASSWORD=memphis
      - POSTGRESQL_DATABASE=memphis
      - POSTGRESQL_PORT_NUMBER=5005
  memphis:
    image: "memphisos/memphis:latest"
    container_name: memphis
    depends_on:
      memphis-metadata:
        condition: service_healthy
    healthcheck:
      test: wget http://127.0.0.1:9000 --spider || exit 1
      interval: 10s
      retries: 30
      start_period: 5s
    restart: on-failure
    pull_policy: always
    ports:
      - "9000:9000"
      - "6666:6666"
      - "7770:7770"
    environment:
      - ROOT_PASSWORD=memphis
      - DOCKER_ENV=true
      - ANALYTICS=true
      - USER_PASS_BASED_AUTH=true
      - CONNECTION_TOKEN=memphis
      - METADATA_DB_HOST=memphis-metadata
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  memphis-rest-gateway:
    image: "memphisos/memphis-rest-gateway:latest"
    container_name: memphis-rest-gateway
    depends_on:
      memphis:
        condition: service_healthy
    restart: on-failure
    pull_policy: always
    ports:
      - "4444:4444"
    environment:
      - JWT_SECRET=JWT_TEST_PURPOSE
      - REFRESH_JWT_SECRET=REFRESH_JWT_TEST_PURPOSE
      - USER_PASS_BASED_AUTH=true
      - CONNECTION_TOKEN=memphis
      - ROOT_USER=root
      - ROOT_PASSWORD=memphis
      - MEMPHIS_HOST=memphis
      - HTTP_PORT=4444




      
