version: "3"

services:
  user-server:
    build: UserManagementService
    container_name: userService
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    restart: on-failure
    env_file:
      - UserManagementService/.env

  mail-server:
    build: EmailService
    container_name: EmailService
    ports:
      - "5001:5001"
    restart: on-failure
    env_file:
      - EmailService/.env

  redis:
    image: redis:7.0.10-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
    restart: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    ports:
      - "27017:27017"

  postgres:
    image: postgres:15.3
    container_name: postgres
    env_file:
      - EventCatalogService/.env
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - /var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11.11-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672



      
