version: "3"

services:
  user-server:
    build: ./userService
    container_name: userService
    ports:
      - 5000:5000
    depends_on:
      - redis
      - mongodb
    restart: on-failure
    env_file:
      - ./userService/.env

  mail-server:
    build: ./emailService
    container_name: emailService
    ports:
      - 5001:5001
    restart: always
    env_file:
      - ./emailService/.env

  redis:
    image: redis:7.0.10-alpine
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
