version: "3"

services:
  user-server:
    build: ./userService
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb 

  mail-server:
    build: ./mailService
    ports:
      - "5001:5001"

  redis:
    image: redis:7.0.10-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017


